[functions]
    directory = "functions"
    node_bundler = "esbuild"

[build]
    publish = "dist"
    command = "npm run build && npm run db-init"
    
[dev]
    framework = "vite"
    autoLaunch = false

[[redirects]]
   from = "/api/*"
   to = "/.netlify/functions/:splat"
   status = 200

[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200
