[functions]
    directory = "functions"
    node_bundler = "esbuild"

[build]
    publish = "dist"
    
[dev]
    autoLaunch = false

[[redirects]]
   from = "/api/*"
   to = "/.netlify/functions/:splat"
   status = 200

[[redirects]]
   from = "/year/:year"
   to = "/index.html?year=:year"
   status = 200
   force = true
