[functions]
    directory = "functions"
    node_bundler = "esbuild"

[build]
    publish = "static"
    
[dev]
    autoLaunch = false

[[redirects]]
   from = "/api/*"
   to = "/.netlify/functions/:splat"
   status = 200
