name: Build

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --message=$MESSAGE
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          MESSAGE: "Commit ${{ github.ref_name }}@${{ github.sha }}"
