name: Preview

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        id: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --message=$MESSAGE
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          MESSAGE: "Commit ${{ github.ref_name }}@${{ github.sha }}"

      - name: Add Message
        uses: unsplash/comment-on-pr@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "This pull request has been deployed to Netlify.\n\n📎 View log:\t${{ steps.deploy.outputs.NETLIFY_LOGS_URL }}\n🔍 Preview:\t${{ steps.deploy.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
