name: Preview

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        if: github.actor != 'dependabot[bot]'
        id: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --message="$MESSAGE"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          MESSAGE: "${{ github.ref_name }}@${{ github.sha }}"

      - name: Comment
        if: steps.deploy.outcome == 'success'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            This pull request has been deployed to Netlify.

            📎 View log: ${{ steps.deploy.outputs.NETLIFY_LOGS_URL }}
            🔍 Preview: ${{ steps.deploy.outputs.NETLIFY_URL }}
