name: Refresh database

on:
  schedule:
    - cron: "0 0 15 * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Update
        run: |
          npm install
          npm run db-update
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
